modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    displayURL="https://github.com/Cursee-Development" #optional
    #logoFile="examplemod.png"
    credits="Thanks to the developers of MultiLoader-Template, Forgix, Botania, Bookshelf, and NeoForge." #optional
    authors="${mod_authors}" #optional
    description='''${mod_description}'''
    #[[mixins]]
    #config="${mod_id}.mixins.json"
    #[[accessTransformers]]
    #file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="SERVER"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
